//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRPProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryID { get; set; }
        public int ProductID { get; set; }
        public int InventoryLane { get; set; }
        public string InventoryRow { get; set; }
        public int InventoryBin { get; set; }
        public int Quantity { get; set; }
    
        public virtual Part Part { get; set; }
    }
}
